# Generated by Django 5.2 on 2026-03-15 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
        migrations.AddField(
            model_name='patient',
            name='avater',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DoctorHospitalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hospital')),
            ],
            options={
                'unique_together': {('doctor', 'hospital')},
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='staff_doctors',
            field=models.ManyToManyField(related_name='hospitals', through='users.DoctorHospitalAssignment', to='users.doctor'),
        ),
    ]
