# Generated by Django 5.2 on 2026-03-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username_alter_doctor_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientHistory',
        ),
    ]
