<<<<<<< HEAD
# Generated by Django 5.2 on 2026-04-12 16:29
=======
# Generated by Django 5.2 on 2026-03-16 22:35
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_patienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='staff_doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
<<<<<<< HEAD
=======
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
>>>>>>> origin/main
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient'),
        ),
<<<<<<< HEAD
=======
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
>>>>>>> origin/main
        migrations.DeleteModel(
            name='DoctorHospitalAssignment',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
