# Generated by Django 5.2 on 2026-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_patienthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='staff_doctors',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Patient'),
        ),
        migrations.DeleteModel(
            name='DoctorHospitalAssignment',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
