# Generated by Django 5.2 on 2026-03-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_specialty_delete_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='avater',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='avater',
            new_name='avatar',
        ),
    ]
