# Generated by Django 5.2 on 2026-04-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='medicalnote',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='medical.appointment'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='history_entry', to='medical.appointment'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='users.patient'),
        ),
        migrations.AddField(
            model_name='weeklyslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_slots', to='users.doctor'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'date', 'time_slot'), name='unique_active_appointment_per_doctor_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together={('doctor', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyslot',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
